'sort_order' => 'score',
'schemadb_config' => 'file:/fi/kilonkipinat/todos/config/config_schemadb.inc',
'schemadb' => 'file:/fi/kilonkipinat/todos/config/schemadb_default.inc',
'schemadb_related' => 'file:/fi/kilonkipinat/todos/config/schemadb_related_default.inc',
'schema' => 'default',

'root_group_to_show' => null,

'categories' => 'Hankinta,Päätös,Selvitys,Maksu,Soitto',
'show_navigation_pseudo_leaves' => true,

'index_entries' => 20,

'enable_notify' => true,