array(
    'mgdschema_class_name' => 'fi_kilonkipinat_forms_expense_lpk',
    'midcom_class_name' => 'fi_kilonkipinat_forms_expense_lpk_dba',
),
array(
    'mgdschema_class_name' => 'fi_kilonkipinat_forms_expense_lpk_line',
    'midcom_class_name' => 'fi_kilonkipinat_forms_expense_lpk_line_dba',
),
array(
    'mgdschema_class_name' => 'fi_kilonkipinat_forms_expense_group',
    'midcom_class_name' => 'fi_kilonkipinat_forms_expense_group_dba',
),
array(
    'mgdschema_class_name' => 'fi_kilonkipinat_forms_expense_group_line',
    'midcom_class_name' => 'fi_kilonkipinat_forms_expense_group_line_dba',
),