array(
    'mgdschema_class_name' => 'fi_kilonkipinat_brainstorm_idea',
    'midcom_class_name' => 'fi_kilonkipinat_brainstorm_idea_dba',
),
array(
    'mgdschema_class_name' => 'fi_kilonkipinat_brainstorm_idea_solution',
    'midcom_class_name' => 'fi_kilonkipinat_brainstorm_idea_solution_dba',
),
array(
    'mgdschema_class_name' => 'fi_kilonkipinat_brainstorm_idea_member',
    'midcom_class_name' => 'fi_kilonkipinat_brainstorm_idea_member_dba',
),
