'schemadb_config' => 'file:/fi/kilonkipinat/account/config/config_schemadb.inc',
'schemadb_person' => 'file:/fi/kilonkipinat/account/config/schemadb_person_default.inc',
'schemadb_jobhistory_jobgroup' => 'file:/fi/kilonkipinat/account/config/schemadb_jobhistory_jobgroup_default.inc',
'schemadb_jobhistory_jobtitle' => 'file:/fi/kilonkipinat/account/config/schemadb_jobhistory_jobtitle_default.inc',
'schemadb_jobhistory_job' => 'file:/fi/kilonkipinat/account/config/schemadb_jobhistory_job_default.inc',
'schema' => 'default',

'root_group_to_show' => null,

'password_min_length' => 8,

'activity_results_per_page' => 30,