array(
    'mgdschema_class_name' => 'fi_kilonkipinat_account_person',
    'midcom_class_name' => 'fi_kilonkipinat_account_person_dba',
),
array(
    'mgdschema_class_name' => 'fi_kilonkipinat_account_jobhistory_jobgroup',
    'midcom_class_name' => 'fi_kilonkipinat_account_jobhistory_jobgroup_dba',
),
array(
    'mgdschema_class_name' => 'fi_kilonkipinat_account_jobhistory_jobtitle',
    'midcom_class_name' => 'fi_kilonkipinat_account_jobhistory_jobtitle_dba',
),
array(
    'mgdschema_class_name' => 'fi_kilonkipinat_account_jobhistory_job',
    'midcom_class_name' => 'fi_kilonkipinat_account_jobhistory_job_dba',
),