'default' => array
(
    'description' => 'Pestiryhmä',
    'fields'      => array
    (
        'name' => Array
        (
            'title' => 'name',
            'storage' => 'name',
            'required' => true,
            'type' => 'urlname',
            'widget' => 'text',
        ),
        'title' => Array
        (
            'title' => 'Otsikko',
            'storage' => 'title',
            'required' => true,
            'type' => 'text',
            'widget' => 'text',
        ),
    ),
),