'schemadb_config' => 'file:/fi/kilonkipinat/accountregistration/config/config_schemadb.inc',
'schemadb_account_search' => 'file:/fi/kilonkipinat/accountregistration/config/schemadb_account_search.inc',

'password_length' => 8,
'username_generation' => 'firstname.lastname',
'require_approval' => true,
'group_to_add' => null,

'mail_sender_address' => 'no-reply@' . $_SERVER['SERVER_NAME'],
'mail_sender_title' => 'no-reply',

'enable_password_reset' => true,
'enable_account_creation' => true,